# Generated by Django 3.1.4 on 2021-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('sales', models.PositiveIntegerField()),
                ('product_line', models.CharField(max_length=100)),
                ('deal_size', models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], max_length=100)),
                ('order_date', models.DateField()),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_number', 'order_date'), name='unique_order_per_month_year'),
        ),
    ]
